# goreleaser v2
version: 2

project_name: emprometheus

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go test ./internal/...

builds:
  - id: emhass
    main: ./cmd/emhass/main.go
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "ghcr.io/beaujr/emprometheus:{{ .Version }}-amd64"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    ids:
      - emhass
  - image_templates:
      - "ghcr.io/beaujr/emprometheus:{{ .Version }}-arm64"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: arm64
    ids:
      - emhass
docker_manifests:
  - name_template: "ghcr.io/beaujr/emprometheus:{{ .Version }}"
    image_templates:
      - "ghcr.io/beaujr/emprometheus:{{ .Version }}-amd64"
      - "ghcr.io/beaujr/emprometheus:{{ .Version }}-arm64"
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Runtime.Goos }}{{ .Runtime.Goarch }}"