# goreleaser v2
version: 2

project_name: emprometheus

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go test ./internal/...

builds:
  - id: emhass
    main: ./cmd/emhass/main.go
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Runtime.Goos }}{{ .Runtime.Goarch }}"