before:
  hooks:
    - go mod tidy
    - go mod vendor
project_name: emprometheus
builds:
  - env:
      - CGO_ENABLED=0
    id: emhass
    main: ./cmd/emhass/main.go
    binary: app
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Runtime.Goos}}{{ .Runtime.Goarch }}"
