version: '3'
services:
  emhass:
    container_name: emhass
    image: ghcr.io/davidusb-geek/emhass:v0.18.0
    volumes:
      - ./emhass_config/share:/share
      - ./emhass_config/data:/data
      - ./emhass_config/secrets_emhass.yaml:/app/secrets_emhass.yaml
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "LOCAL_COST_FUN=profit" # Maximizes profit (exports - imports)
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - emprometheus
  promhass:
    container_name: promhass
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: integration
    command: [ "--emhass_url", "http://emhass:5000", "--dir", "/data" ]
    volumes:
      - ./emhass_config/share:/share
      - ./emhass_config/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - emprometheus
networks:
  emprometheus:
    driver: bridge   # Specify driver options
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"