apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promhass.fullname" . }}
  labels:
    {{- include "promhass.labels" . | nindent 4 }}
data:
  config.json:
  {{ .Values.config | toYaml | indent 4}}
  secrets.yaml:
  {{ .Values.secrets | toYaml | indent 4 }}