apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promhass.fullname" . }}
  labels:
    {{- include "promhass.labels" . | nindent 4 }}
data:
  config.json: |-
  {{ merge .Values.config (dict "optimization_time_step"  (div 1440 .Values.steps) ) | toJson | indent 4 }}
  secrets.yaml:
  {{ .Values.secrets | toYaml | indent 4 }}