apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "promhass.fullname" . }}
  labels:
    {{- include "promhass.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "promhass.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/pod: "{{ printf "%s" (now | unixEpoch) }}"
      labels:
        app: promhass
        {{- include "promhass.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "promhass.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.promhass_image.repository }}:{{ .Values.promhass_image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.promhass_image.pullPolicy }}
          args:
            - --server
          {{- with .Values.promhass.args }}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: promhasshttp
              containerPort: {{ .Values.promhass_service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.promhass_service.metrics }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: emhass
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.emhass_image.repository }}:{{ .Values.emhass_image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.emhass_image.pullPolicy }}
          env:
            - name: SECRETS_PATH
              value: /secrets_emhass.yaml
          ports:
            - name: emhasshttp
              containerPort: {{ .Values.emhass_service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
