name: Autotag and release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create new version tag
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --list "v*" --sort=-v:refname | head -n 1)

          if [ -z "$LAST_TAG" ]; then
            NEW_TAG="v0.1.0"
          else
            VERSION=${LAST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          fi

          git tag $NEW_TAG
          git push origin $NEW_TAG
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Container Login
        uses: docker/login-action@v4.4.0
        with:
          registry: containers.whickerx.info
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Get Values.yaml
        env:
          VALUES: ${{ secrets.VALUES }}
        run: mkdir -p charts/values/ && echo $VALUES  | base64 -d > charts/values/cloud.yaml
      - name: Get k8s setup
        env:
          KUBECONF: ${{ secrets.KUBECONF }}
        run: mkdir -p ~/.kube/ && echo $KUBECONF  | base64 -d > ~/.kube/config
      - name: Deploy
        run: helm upgrade --install promhass charts/promhass --set promhass_image.tag=$(git rev-parse --short HEAD) -f charts/values/cloud.yaml
